### ISSUE TITLE
Things to do:

### ISSUE THREAD

**Issue by smz** [smz/Arduino-RTCtime#2]
- [x] Have a version of SetTime() taking a time_t value instead of a "struct_tm"
 - [x] Have a version of GetTime returning a "struct tm" instead of a time_t value
 - [x] Add more examples for enhanced features
 - [x] Add support for more hardware

**Comment by smz** [comment]
I'm not planning to add support for more hardware at this time, so I'm closing this issue.

If the need will arise (_for my personal use or on someone's else request_) support for different hardware could always be added in the future...

**Comment by dragoblaztr** [comment]
So, isn't possible to set the date and time by any interface ? or how would it be possible?

Regards

**Comment by smz** [comment]
Sorry @dragoblaztr, I'm not getting what you mean...
Of course it is possible to "_set the date and time_", but what do you mean with "_by any interface_"?
Have you seen the `SetTime()` and `SetTimeUX()` methods?
Can you please be more specific?

**Comment by dragoblaztr** [comment]
I want to change it, by a 4x4 keypad, I already have the code for get the keys but for change the date through it, wich function and what parameters are required.

Regards

**Comment by smz** [comment]
Sorry, but this goes very much beyond being a specific "issue" of this library and is a very broad question of general Arduino programming which is inappropriate here, especially in a **closed** issue.
In any case the `SetTime()` or `SetTimeUX()` methods, as I said, are what you are looking for. Which one will be better for you depends on how you store date-time internally (_as explained in the project main page_).

**Comment by smz** [comment]
Locking this conversation as it was abused for irrelevant comments
